export const resources = [
  "organization",
  "users",
  "devices",
  "roles",
  "streams",
  "views",
  "channels",
  "comments",
  "teleop",
  "terminal",
  "portForwarding",
  "events",
  "commands",
  "annotations",
  "capture",
  "share",
  "fileStorage",
  "integrations",
  "interventions",
  "analytics",
  "keyValueStorage",
  "schedules",
  "kiosk",
  "billing",
  "taskSummaries",
] as const;
