env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
  - "plugin:import/typescript"
  - "plugin:jest/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier
  - jest
rules:
  "prettier/prettier": ["error"]
  "import/extensions":
    ["error", "ignorePackages", { "ts": "never", "tsx": "never" }]
  "react/jsx-filename-extension": ["error", { "extensions": [".tsx", ".jsx"] }]
  "import/no-extraneous-dependencies": "off"
  "import/prefer-default-export": "off"
  "lines-between-class-members": "off"
  "no-useless-return": "off"
  "no-underscore-dangle": "off"
  "no-use-before-define": "off"
  "no-unused-vars": "off"
  "consistent-return": "off"
  "default-case": "off"
  "arrow-body-style": "off"
  "no-new": "off"
  "no-promise-executor-return": "off"
  "no-else-return": "off"
  "no-param-reassign": "off"
  "no-restricted-syntax": "off"
  "prefer-template": "off"
  "no-restricted-properties": "off"
  "no-useless-escape": "off"
  "prefer-exponentiation-operator": "off"
  "no-shadow": "off"
  "no-return-await": "off"
  "getter-return": "off"
  "no-empty-function": "off"
  "no-useless-constructor": "off"
  "class-methods-use-this": "off"
  "no-plusplus": "off"
  "no-await-in-loop": "off"
  "no-inner-declarations": "off"
  "prefer-destructuring": "off"
  "no-nested-ternary": "off"
  "array-callback-return": "off"
  "react/require-default-props": "off"
  "react/prefer-stateless-function": "off"
  "react/no-array-index-key": "off"
  "jsx-a11y/anchor-is-valid": "off"
  "no-restricted-globals": "off"
  "react/prop-types": "off"
  "import/no-unresolved": "off"
  "import/no-webpack-loader-syntax": "off"
  "import/newline-after-import": "off"
  "no-undef": "off"
  "react/sort-comp": "off"
  "react/destructuring-assignment": "off"
  "react/function-component-definition": "off"
  "react/jsx-props-no-spreading": "off"
  "react/no-unused-class-component-methods": "off"
  "jsx-a11y/label-has-associated-control": "off"
  "no-return-assign": "off"
  "react/no-unused-prop-types": "off"
  "react/jsx-fragments": "off"
  "react/jsx-no-useless-fragment": "off"
  "react/button-has-type": "off"
  "react/jsx-boolean-value": "off"
  "jsx-a11y/iframe-has-title": "off"
  "import/no-relative-packages": "off"
  "import/no-dynamic-require": "off"
  "no-continue": "off"
  "import/no-cycle": "off"
  "import/no-mutable-exports": "off"
  "import/no-useless-path-segments": "off"
  "no-case-declarations": "off"
  "react/no-unescaped-entities": "off"
  "spaced-comment": "off"
  "no-unneeded-ternary": "off"
  "react/jsx-no-bind": "off"
  "global-require": "off"
  "new-cap": "off"
  "operator-assignment": "off"
  "no-extra-bind": "off"
  "no-unsafe-optional-chaining": "off"
  "no-lonely-if": "off"
  "prefer-const": "off"
  "no-multi-assign": "off"
  "jsx-a11y/control-has-associated-label": "off"
  "prefer-promise-reject-errors": "off"
  "no-sequences": "off"
  "jsx-a11y/no-static-element-interactions": "off"
  "jsx-a11y/alt-text": "off"
  "react/style-prop-object": "off"
  "no-bitwise": "off"
  "no-irregular-whitespace": "off"
  "no-self-assign": "off"
  "jsx-a11y/click-events-have-key-events": "off"
  "jsx-a11y/no-autofocus": "off"
  "no-redeclare": "off"
  "jsx-a11y/no-noninteractive-tabindex": "off"
  "react/jsx-no-target-blank": "off"
  "no-self-compare": "off"
  "react/no-unstable-nested-components": "off"
  "react/no-arrow-function-lifecycle": "off"
  "react/jsx-curly-brace-presence": "off"
  "jsx-a11y/mouse-events-have-key-events": "off"
  "no-extra-boolean-cast": "off"
  "import/no-duplicates": "off"
  "no-loop-func": "off"
  "react/no-deprecated": "off"
  "no-useless-rename": "off"
  "jsx-a11y/media-has-caption": "off"
  "no-useless-catch": "off"
  "no-dupe-class-members": "off"
  "import/no-import-module-exports": "off"
  "no-throw-literal": "off"
  "camelcase": "off"
  "prefer-object-spread": "off"
  "default-param-last": "off"
  "no-ex-assign": "off"
  "no-empty-pattern": "off"
