import { DataLayer } from "./layers/DataLayer";
import { LabelLayer } from "./layers/LabelLayer";
import { LayerRegistry } from "./layers/LayerRegistry";
import { TransformLayer } from "./layers/TransformLayer";
import { GroundLayer } from "./layers/GroundLayer";
import { ImageLayer } from "./layers/ImageLayer";
import { GltfLayer } from "./layers/GltfLayer";
import { GridMapLayer } from "./layers/GridMapLayer";
import { GeometryLayer } from "./layers/GeometryLayer";
import { PointCloudLayer } from "./layers/PointCloudLayer";
import { HardwareVideoLayer } from "./layers/HardwareVideoLayer";
import { DeviceVisualUrdfLayer } from "./layers/DeviceVisualUrdfLayer";
import { DeviceVisualTFLayer } from "./layers/DeviceVisualTFLayer";

export * from "./components/Universe";
export * from "./model/IUniverseData";
export * from "./layers/LayerRegistry";
export * from "./layers/UniverseLayer";
export * from "./layers/TransformLayer";
export * from "./components/sidebar";
export * from "./model/SceneGraph";
export * from "./objects/Label";

LayerRegistry.register(DataLayer);
LayerRegistry.register(LabelLayer);
LayerRegistry.register(TransformLayer);
LayerRegistry.register(GroundLayer);
LayerRegistry.register(ImageLayer);
LayerRegistry.register(GltfLayer);
LayerRegistry.register(GroundLayer);
LayerRegistry.register(GridMapLayer);
LayerRegistry.register(GeometryLayer);
LayerRegistry.register(PointCloudLayer);
LayerRegistry.register(DeviceVisualUrdfLayer);
LayerRegistry.register(DeviceVisualTFLayer);
LayerRegistry.register(HardwareVideoLayer);
