env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
  - "plugin:import/typescript"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules:
  "import/extensions":
    [
      "error",
      "ignorePackages",
      { "ts": "never", "tsx": "never", "js": "never" },
    ]
  "react/jsx-filename-extension": ["error", { "extensions": [".tsx", ".jsx"] }]
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars":
    [
      "warn",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
      },
    ]
  "import/no-relative-packages": "off"
  "no-param-reassign": ["error", { "props": false }]
  "import/prefer-default-export": "off"
  "class-methods-use-this": "off"
  "react/destructuring-assignment": "off"
  "react/no-unescaped-entities": "off"
  "react/no-unused-class-component-methods": "off"
  "react/require-default-props": "off"
  "import/no-cycle": "off"
  "react/jsx-no-bind": "off"
  "jsx-a11y/click-events-have-key-events": "off"
